backend:
  name: github
  repo: nop33/si
  branch: update-content

media_folder: src/images
public_folder: src/images

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Featured image", name: "featuredImage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Featured in home page Events section",
          name: "isEventFeaturedOnHomepage",
          widget: "boolean",
          default: false,
          required: false,
        }
      - label: "SEO"
        name: "seo"
        widget: object
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: false,
            }
  - name: "member"
    label: "Team member"
    folder: "src/content/member"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{name}}/index"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - label: "Group"
        name: "group"
        widget: "select"
        options:
          ["Advisers", "Governing board", "Collaborators", "Staff", "Alumni"]
      - { label: "Role", name: "role", widget: "string" }
      - label: "External links"
        name: "links"
        widget: "object"
        required: false
        fields:
          - {
              label: "Website",
              name: "website",
              widget: "string",
              required: false,
            }
          - {
              label: "Twitter",
              name: "twitter",
              widget: "string",
              required: false,
            }
          - {
              label: "LinkedIn",
              name: "linkedin",
              widget: "string",
              required: false,
            }
      - {
          label: "Disable detail page",
          name: "disableDetailPage",
          widget: boolean,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "SEO"
        name: "seo"
        widget: object
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: false,
            }
